spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/test_h2;DB_CLOSE_ON_EXIT=FALSE
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/test
#    xa:
#      data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
  jooq:
    sql-dialect: H2
jpa:
    generate-ddl: true



