spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/test_h2
  data:
    mongodb:
      #database: picture
      #password: picture
      #username: picture
      database: test
      password: admin
      username: admin
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
jpa:
    generate-ddl: true

