spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/test_h2
  data:
    mongodb:
      database: picture
      password: picture
      username: picture
      #database: test
      #password: admin
      #username: admin
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  cache:
    jcache:
      #provider: org.ehcache.jcache.JCacheCachingProvider
      #provider: com.hazelcast.cache.HazelcastCachingProvider
      #provider: org.infinispan.jcache.embedded.JCachingProvider
    cache-names: need
    #infinispan:
      #config: infinispan.xml
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pooled: true
  artemis:
    mode: native
    host: localhost
    port: 61616
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
jpa:
    generate-ddl: true



