spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/test_h2
  data:
    mongodb:
      database: picture
      password: picture
      username: picture
      #database: test
      #password: admin
      #username: admin
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  cache:
    jcache:
      #provider: org.ehcache.jcache.JCacheCachingProvider
      #provider: com.hazelcast.cache.HazelcastCachingProvider
      #provider: org.infinispan.jcache.embedded.JCachingProvider
    cache-names: need
    #infinispan:
      #config: infinispan.xml
jpa:
    generate-ddl: true


