/**
 * This class is generated by jOOQ
 */
package com.hopever.springexample.db.jooq;


import com.hopever.springexample.db.jooq.tables.Test;
import com.hopever.springexample.db.jooq.tables.records.TestRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>TEST_SCHEMA</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<TestRecord, Long> IDENTITY_TEST = Identities0.IDENTITY_TEST;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<TestRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<TestRecord, Long> IDENTITY_TEST = createIdentity(Test.TEST, Test.TEST.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<TestRecord> CONSTRAINT_2 = createUniqueKey(Test.TEST, Test.TEST.ID);
	}
}
