/**
 * This class is generated by jOOQ
 */
package com.hopever.springexample.db.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in TEST_SCHEMA
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>TEST_SCHEMA.SYSTEM_SEQUENCE_8F2C1250_A17F_43D0_A458_766CA8AA7FD7</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_8F2C1250_A17F_43D0_A458_766CA8AA7FD7 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_8F2C1250_A17F_43D0_A458_766CA8AA7FD7", TestSchema.TEST_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);
}
