/**
 * This class is generated by jOOQ
 */
package com.hopever.springexample.db.jooq;


import javax.annotation.Generated;

import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestSchema extends SchemaImpl {

	private static final long serialVersionUID = -164006207;

	/**
	 * The reference instance of <code>TEST_SCHEMA</code>
	 */
	public static final TestSchema TEST_SCHEMA = new TestSchema();

	/**
	 * No further instances allowed
	 */
	private TestSchema() {
		super("TEST_SCHEMA");
	}
}
