security:
    oauth2:
        client:
            clientId: tonr
            clientSecret: secret
            accessTokenUri: http://localhost:8080/oauth/token
            userAuthorizationUri: http://localhost:8080/oauth/authorize
            #clientAuthenticationScheme: form
        resource:
            userInfoUri: http://localhost:8080/photos/user/single
            preferTokenInfo: false