/**
 * This class is generated by jOOQ
 */
package com.hopever.springexample.db.jooq.h2;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in TEST_SCHEMA
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>TEST_SCHEMA.SYSTEM_SEQUENCE_82E84F80_507E_48F4_9107_518E68FEEFC9</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_82E84F80_507E_48F4_9107_518E68FEEFC9 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_82E84F80_507E_48F4_9107_518E68FEEFC9", TestSchema.TEST_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);
}
