/**
 * This class is generated by jOOQ
 */
package com.hopever.springexample.db.jooq.h2;


import com.hopever.springexample.db.jooq.h2.tables.Test;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in TEST_SCHEMA
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table TEST_SCHEMA.TEST
	 */
	public static final Test TEST = com.hopever.springexample.db.jooq.h2.tables.Test.TEST;
}
