/**
 * This class is generated by jOOQ
 */
package com.hopever.springexample.db.jooq.h2;


import com.hopever.springexample.db.jooq.h2.tables.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestSchema extends SchemaImpl {

	private static final long serialVersionUID = -1388957684;

	/**
	 * The reference instance of <code>TEST_SCHEMA</code>
	 */
	public static final TestSchema TEST_SCHEMA = new TestSchema();

	/**
	 * No further instances allowed
	 */
	private TestSchema() {
		super("TEST_SCHEMA");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.SYSTEM_SEQUENCE_82E84F80_507E_48F4_9107_518E68FEEFC9);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Test.TEST);
	}
}
